[project]
name = "amo-route-plan"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "folium>=0.20.0",
    "matplotlib>=3.10.6",
    "networkx>=3.5",
    "pyproj>=3.7.2",
    "shapely>=2.1.1",
]
